### ISSUE TITLE
Update Paexo wearable device to serialize wearable data/commands to access through yarp ports

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/wearables#109]
Currently the [Paexo wearable device](https://github.com/robotology/wearables/tree/master/devices/Paexo) just exposes wearable data from the actual Paexo exoskeleton.
To enable developing matlab controllers for the Paexo, we need to serialize wearable data to be data through yarp ports, also a way to handle the motor commands through receive data from a yarp port.

This issue tracks the details related to addressing this task

CC @lrapetti @claudia-lat @DanielePucci

**Comment by Yeshasvitvs** [comment]
>  we need to serialize wearable data to be data through yarp ports

Thanks to @prashanthr05 for https://github.com/robotology/wearables/pull/113 we can realize this wearable data streaming to yarp ports through the new logger

> a way to handle the motor commands through receive data from a yarp port.

At the moment the Paexo wearable device has an rpc port https://github.com/robotology/wearables/blob/master/devices/Paexo/src/Paexo.cpp#L209, and we can use the `YarpRpc` block from https://github.com/robotology/wb-toolbox/pull/178 to send motor commands to Paexo device. 

@diegoferigo please take a look at https://github.com/robotology/wb-toolbox/pull/178#issuecomment-644711133, and let me know if we can proceed with that PR.

CC @lrapetti @claudia-lat

**Comment by traversaro** [comment]
> @diegoferigo please take a look at [robotology/wb-toolbox#178 (comment)](https://github.com/robotology/wb-toolbox/pull/178#issuecomment-644711133), and let me know if we can proceed with that PR.

I think I can give feeedback in the PR as we transitioned the maintenance of the repo to me.

**Comment by Yeshasvitvs** [comment]
> Thanks to @prashanthr05 for #113 we can realize this wearable data streaming to yarp ports through the new logger

For communication of Paexo wearable data to yarp ports that can be read in simulink, the PR #123 updates iwear logger device with yarp functionality.


For communication from simulink to Paexo, an alternative to yarp rpc block is to update the Paexo wearable device with yarp ports that receive motor commands. Furthermore, having two separate Left and Right motor actuators is needed. This is implemented and tested in [Paexo/motor-control-yarp](https://github.com/robotology/wearables/tree/Paexo/motor-control-yarp)


Following the above two changes, I wrote a simple simulink controller using `WBToolBox` to read the Paexo data using `yarp read` blocks and sending motor commands through `yarp write` blocks.


https://user-images.githubusercontent.com/6505998/123477543-7ff36880-d5fe-11eb-82ef-e68ade8ee304.mp4

The entire pipeline works fine, except for high frequency motor commands to the Paexo. This needs to be investigated further.


https://user-images.githubusercontent.com/6505998/123477740-c47f0400-d5fe-11eb-8f9a-f2494c68eaba.MOV


https://user-images.githubusercontent.com/6505998/123477743-c5b03100-d5fe-11eb-90e5-90b5b0aac5a3.MOV

CC @claudia-lat @lrapetti @DanielePucci

**Comment by lrapetti** [comment]
I think this issue was completed, @claudia-lat @Yeshasvitvs can we close it?
