### ISSUE TITLE
Write README.md

### ISSUE THREAD

**Issue by diegoferigo** [robotology/wearables#14]

**Comment by lrapetti** [comment]
One thing that should be mentioned in the `README.md` is that it may be required to export the installation directory to `IWear_DIR` environment variable.

**Comment by traversaro** [comment]
@lrapetti Alternativly you may just append the installation prefix to the `CMAKE_PREFIX_PATH` enviroment variable.

**Comment by claudia-lat** [comment]
@lrapetti @Yeshasvitvs please understand if we have to close this issue.

**Comment by lrapetti** [comment]
Preliminary documentation on how to use the wearable devices is there, we still miss documentation regarding the compilation. Probably we should add it before closing, I move this in backlog so that we can achieve it in the next Iteration.

**Comment by lrapetti** [comment]
> Preliminary documentation on how to use the wearable devices is there, we still miss documentation regarding the compilation.

I have add this documentation with https://github.com/robotology/wearables/pull/96. I will close this issue, feel free to open new issues in case you think any essential information is still missing.
