### ISSUE TITLE
Cleanup use of YARP deprecated methods

### ISSUE THREAD

**Issue by traversaro** [robotology/wearables#151]
YARP deprecated methods such as `asDouble` are used in the codebase, for example in https://github.com/robotology/wearables/blob/b42357accfd6c02530417d909fb124b41ccbc083/modules/IWearFrameVisualizer/src/main.cpp#L267 . That code will not compile once https://github.com/robotology/yarp/pull/2833 is merged.

**Comment by lrapetti** [comment]
Done in https://github.com/robotology/wearables/pull/152
