### ISSUE TITLE
CI failing on Ubuntu and MacOS

### ISSUE THREAD

**Issue by lrapetti** [robotology/wearables#160]
As per the title

**Comment by traversaro** [comment]
See https://github.com/robotology/gazebo-yarp-plugins/pull/631 .

**Comment by lrapetti** [comment]
> See [robotology/gazebo-yarp-plugins#631](https://github.com/robotology/gazebo-yarp-plugins/pull/631) .

Thanks @traversaro, PR opened https://github.com/robotology/wearables/pull/161

**Comment by lrapetti** [comment]
CI is back! Closing
