### ISSUE TITLE
Update termination procedure of wearable components

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/wearables#37]
Following the [Investigate and Fix segmentation fault on HDE termination](https://github.com/robotology/human-dynamics-estimation/issues/109) issue, I noticed that the termination procedure for the wearable components is also incorrect. In this issue we track the details on fixing the termination procedure for wearable components. 

The branch is https://github.com/robotology/wearables/tree/fix/update-termination-process

@lrapetti @diegoferigo @traversaro @DanielePucci

**Comment by DanielePucci** [comment]
@Yeshasvitvs  please open a iCub PR.

**Comment by DanielePucci** [comment]
@Yeshasvitvs could you please update and detail this issue?

**Comment by Yeshasvitvs** [comment]
The termination process is fine on linux machine but we noticed that on mac machine it is not clean. The last test we did was on @lrapetti machine. @lrapetti can you please update this issue if you tried to double check this patch further. Thanks.

**Comment by DanielePucci** [comment]
It needs to be teste on Mac @lrapetti

**Comment by lrapetti** [comment]
I tested the `master` and terminate correctly, while I get segmentation fault on termination for `feature/ICub-dev-impl`

**Comment by Yeshasvitvs** [comment]
@lrapetti Please test the branch https://github.com/robotology/wearables/commit/575c6342dfab709d6af09f334043aa2cebfca4d1

Once it is tested we can merge to `master` and then proceed to also merge `feature/ICub-dev-impl` to `master`

**Comment by lrapetti** [comment]
New PR at https://github.com/robotology/wearables/pull/50

**Comment by Yeshasvitvs** [comment]
The PR #50 is merged, closing this issue.
