### ISSUE TITLE
Test wearables yarpmanager application 

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/wearables#39]
Following the creation of yarpmanager application for wearables https://github.com/dic-iit/component_andy/issues/195 in this issue we will test if all the components can be launched correctly.

CC @lrapetti

**Comment by Yeshasvitvs** [comment]
@lrapetti we should test this as early as possible and close this issue. It will help to launch the demos directly using yarpmanager and reduces bus factor.

**Comment by lrapetti** [comment]
I was testing the `yarpmanager` application on Windows laptop using the [`Wearables-yarpmanager.ini`](https://github.com/robotology/wearables/blob/feature/ICub-device-impl/app/Wearables-yarpmanager.ini) file in the branch `ICub-device-impl` but I noticed that the files are not installed and the applications get stuck as they try to find the files.

**Comment by Yeshasvitvs** [comment]
@lrapetti HDE laptop and icub30 laptop may have local changes on wearables and HDE which I had to do for pHRI rviz visualization. Please double check this when trying to run anything. If possible stash the changes as we still have to get rviz visualization.

**Comment by Yeshasvitvs** [comment]
@lrapetti any update on this ?

**Comment by Yeshasvitvs** [comment]
@lrapetti may be we can close this issue ?

**Comment by lrapetti** [comment]
> @lrapetti may be we can close this issue ?

I think so, we already used some of those application
