### ISSUE TITLE
Move to Robotology?

### ISSUE THREAD

**Issue by kouroshD** [robotology/wearables#41]
Since we are planning to add HDE to robotology-superbuild, I think it is a good occasion to move this repo to robotology, since it is stable as well.
What do you think and suggest @traversaro ?

cc @DanielePucci  @Yeshasvitvs  @lrapetti  @claudia-lat @diegoferigo

**Comment by traversaro** [comment]
I totally agree!

**Comment by DanielePucci** [comment]
**go!**

**Comment by diegoferigo** [comment]
Double thumbs up!

**Comment by kouroshD** [comment]
Since I do not have the permission at organizational level, I cannot proceed further for this issue.
Also, I suggest @Yeshasvitvs  follow this issue, since he is supposed to be the maintainer of the `Human_Dynamics` profile.

@traversaro  @diegoferigo  What do you suggest? should we move the repo to the other organization or we should fork it?

**Comment by traversaro** [comment]
I can move it, thanks!

**Comment by traversaro** [comment]
Done.
