### ISSUE TITLE
Enable the Installation of the xml file

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/wearables#62]
The `xml` files stored in [app](https://github.com/robotology/wearables/tree/master/app) are not installed when `make install` is executed. This forces to run 
`yarprobotinterface --config XsensSuitWearableDevice.xml` in the `app/xml/` folder.

The problem can be easily solved by installing the files using the following command in the `CMakeLists.txt` file
```cmake
 yarp_install(DIRECTORY xml DESTINATION ${YARP_CONTEXTS_INSTALL_DIR})
```

**Comment by kouroshD** [comment]
The PR https://github.com/robotology/wearables/pull/63 is closed and we can close this issue.
