### ISSUE TITLE
Improve CMake files

### ISSUE THREAD

**Issue by lrapetti** [robotology/wearables#68]
Following https://github.com/robotology/wearables/pull/65#issuecomment-556065310

**Comment by lrapetti** [comment]
With https://github.com/robotology/wearables/pull/71 the changes in the cmake files are reverted, so we have again the scoping of the thrift dependencies. 

Probably cleanup is no longer required and we can close this issue, what do you think @diegoferigo?

**Comment by diegoferigo** [comment]
Yep we can close the issue
