### ISSUE TITLE
Develop FTShoes

### ISSUE THREAD

**Issue by diegoferigo** [robotology/wearables#7]
This new class is one of the implementations of the `IWear` interface. It will expose the data from the [ftShoe](https://github.com/robotology-playground/forcetorque-yarp-devices/tree/master/ftShoe), particularly:

- FT sensors
- IMUs
- Temperature sensors

**Comment by lrapetti** [comment]
`FTShoes` has been developed (https://github.com/robotology-playground/wearables/tree/master/devices/FTShoes). 
@diegoferigo @Yeshasvitvs if you agree, we can close this issue.

**Comment by diegoferigo** [comment]
In my opinion we should wait the development of the device that wraps `MultipleAnalogSensor` interfaces to an `IWear` interface. Right now only the FTSensors have been implemented, using the old `IAnalogSensor` interface.

**Comment by lrapetti** [comment]
> In my opinion we should wait the development of the device that wraps `MultipleAnalogSensor` interfaces to an `IWear` interface. Right now only the FTSensors have been implemented, using the old `IAnalogSensor` interface.

This missing part is related to #18. Closing this issue since an implementation of FTShoe is available.
